public enum TipoTela {
	PRINCIPAL,
  // Imovel
  IMOVEL,
  ALUGAR_IMOVEL,
	CADASTRO_IMOVEL,
  LISTAR_IMOVEIS,
  BLOQUEAR_IMOVEL,
  ESCOLHA_TIPO_IMOVEL,
  CALC_VAL_REF_IMOVEL,
  CADASTRO_CONDOMINIO, // TODO
  LISTAR_CONDOMINIO,   // TODO

  // Proprietario
  PROPRIETARIO,
  SELECIONAR_PROPRIETARIO,
	CADASTRO_PROPRIETARIO,
}
